name: Rubocop Checks

on: push

jobs:
  rubocop_check:
    name: RuboCop Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby 2.5.1
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5.x
      - name: Installing Dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: RuboCop Check
        uses: gimenete/rubocop-action@1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}